### ISSUE TITLE
auth的result返回值和最新的有赞云不符，accessToken应该是access_token

### ISSUE THREAD

**Issue by guoqchen1001** [xu42/youzan-sdk-go#1]
accessToken应该是access_token

**Comment by xu42** [comment]
@guoqchen1001 有空的话提一个PR吧。
PS: 这个SDK后面可能要大改一下，现在的对使用者不太友好。

**Comment by xu42** [comment]
Fixed in https://github.com/xu42/youzan-sdk-go/pull/2
